- name : Preparing local environment for jail 
  set_fact:
    jail_temp: "{{ 99999999999999999995 | random | to_uuid }}.jail"
    user_temp: "{{ 99999999999999999995 | random | to_uuid }}.user"

- name:  Create jail config  for {{ jail_name }}
  ansible.builtin.template:
    src: files/jail_template.conf
    dest: /tmp/{{jail_temp}}

- name: Remove jail {{ jail_name }} 
  become: true
  shell:
       cmd: >
              jail -r {{ jail_name }}
  ignore_errors: yes 

- name: Unmount jail {{ jail_name }} 
  become: true
  shell:
       cmd: >
              zfs umount -f /{{jail_dir}}/{{jail_name}}
  ignore_errors: yes 

- name: Destroy jail {{ jail_name }} 
  shell:
     cmd:  > 
         zfs destroy -r {{ jail_dataset }}/{{jail_name}}

- name: Creating jail  {{ jail_name }} with ip address  {{ ip }}
  become: true
  shell:
       cmd: >
              jail -cmf /tmp/{{jail_temp}}

- name: Setting sshd_enable=YES {{ jail_name }} with ip address  {{ ip }}
  become: true
  shell:
       cmd: >
              jexec {{ jail_name }}  sysrc sshd_enable=YES

- name: Starting sshd service 
  become: true
  shell:
       cmd: >
               jexec {{ jail_name }} service sshd onestart
  ignore_errors: yes 

- name: Creating file for user {{ user }} 
  copy:
      dest: "/{{jail_dir}}/{{jail_name}}/tmp/{{ user_temp }}"
      content: |
              {{user}}::::::::/bin/sh:{{pass}}

- name: Adding user to jail {{ jail_name }} format is name:uid:gid:class:change:expire:gecos:home_dir:shell:password
  become: true
  shell: 
     cmd: > 
       jexec {{ jail_name }} adduser -f  /tmp/{{ user_temp }}  
  register: out
  ignore_errors: yes 

- name: Create .ssh directory exists for user {{ user }}
  file: 
     path:  /{{jail_dir}}/{{jail_name}}/home/{{ user }}/.ssh
     state: directory

- name: Adding ssh-key for user {{ user }} 
  copy:
      dest: "/{{jail_dir}}/{{jail_name}}/home/{{ user }}/.ssh/authorized_keys"
      content: |
              {{ ssh_key }}
