---
- name : Preparing local environment
  set_fact:
    #base: "{{ 99999999999999999995 | random | to_uuid }}-base.txz"
    base: base.txz
    jail_dir: "{{  jail_dataset.split('/')[1] }}"

- name: Loading kernel modules for using netgraph for vnet jails
  shell:
    cmd: > 
         kldload ng_ether
         kldload pf
  ignore_errors: yes 

- name: Copying jng script to /usr/local/bin to create vnet jails using netgraph
  shell:
    cmd: > 
         cp /usr/src/share/examples/jails/jng  /usr/local/bin/jng
  ignore_errors: yes 

- name : Reading Old /etc/devfs.rules
  command: cat /etc/devfs.rules  
  register: devfs_command_output

- name: Print Old /etc/devfs.rules
  debug:
    msg: "{{devfs_command_output.stdout_lines}}"
 
- name: Creating devfs rules for jails
  copy:
      dest: "/etc/devfs.rules"
      content: |
                 [devfsrules_jail=11]
                 add include $devfsrules_hide_all
                 add include $devfsrules_unhide_basic
                 add include $devfsrules_unhide_login
                 add path 'bpf*' unhide
                 add path 'pf*' unhide
                 add path 'pflog' unhide
                 add path 'pfsynv' unhide
                 [devfsrules_jail=1]
                 add include $devfsrules_hide_all
                 add include $devfsrules_unhide_basic
                 add include $devfsrules_unhide_login
                 add include $devfsrules_jail
                 [devfsrules_jail=5]
                 add include $devfsrules_hide_all
                 add include $devfsrules_unhide_basic
                 add include $devfsrules_unhide_login
                 add path 'tun*' unhide
                 add path zfs unhide
                 [devfsrules_jail=12]
                 add include $devfsrules_hide_all
                 add include $devfsrules_unhide_basic
                 add include $devfsrules_unhide_login
                 add path 'bpf*' unhide
                 add include $devfsrules_jail
                 add path 'bpf*' unhide
                 add path 'zfs*' unhide
                 add path 'pf*' unhide
                 add path 'pflog' unhide
                 add path 'pfsynv' unhide
                 add path 'dtrace*' unhide
                 add path dtrace/* unhide
  ignore_errors: yes 

- name: Checking if base jail exists if exists, no base jail will be created
  stat:
      path: /tmp/{{ base }}
  register: base_stat_result

- name: Checking if base.txz exists if exists, it will not be fetched again
  stat:
      path: /{{jail_dir}}/{{ base_jail }}
  register: base_jail_stat_result

- name: Create dataset for jails 
  shell:
      cmd: >
              zfs create -o mountpoint=/"{{jail_dir}}"  "{{ jail_dataset }}"   
  ignore_errors: yes 
  when: not base_jail_stat_result.stat.exists

- name : Fetching base.txz jail for {{ rel  }} RELEASE {{ arch }} 
  shell:
     cmd: >
              fetch  'https://download.freebsd.org/ftp/releases/{{ arch  }}/{{ rel }}-RELEASE/base.txz' -o '/tmp/{{ base }}'
  when: not base_stat_result.stat.exists

- name : Creating base jail  {{ base_jail }}
  shell:
      cmd: >
              zfs create '{{ jail_dataset }}/{{ base_jail }}'
  ignore_errors: yes 
  when: not base_jail_stat_result.stat.exists

- name : Populating  base jail with base for {{ rel  }} RELEASE 
  become: yes 
  shell: 
    cmd: > 
           tar  -xf /tmp/{{ base  }} -C  /{{ jail_dir }}/{{ base_jail }}/
  when: not base_jail_stat_result.stat.exists


- name : Taking snapshot for base jail for {{ rel  }} RELEASE 
  shell:
      cmd: >
              zfs snapshot '{{ jail_dataset}}/{{ base_jail }}@{{ snapshot_name }}'
  when: not base_jail_stat_result.stat.exists

- name :  Cleanup temp files
  shell:
      cmd: >
              rm /tmp/"{{ base }}"
  when: not base_jail_stat_result.stat.exists
